name: release and push to central
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        env:
          #          staging
          ORG_GRADLE_PROJECT_stagingUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_stagingPassword: ${{ secrets.OSSRH_TOKEN }}
          ORG_GRADLE_PROJECT_signingKeyId: 3EE3EB8A
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingKeyPassword: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          settings-path: ${{ github.workspace }} # location for the settings.xml file
#          server-id: ossrh
#          server-username: ${{ secrets.OSSRH_USERNAME }}
#          server-password: ${{ secrets.OSSRH_TOKEN }}
#          TODO- use a diff var for this
#          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
#          gpg-passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
#      - name: build artifact
#        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
#        with:
#          arguments: build
      - name: Publish to the Maven Central Repository
#        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        run: |
          echo env
          ./gradlew assemble publish
#        with:
#          arguments: publish
